import { ParkingSpot } from "./types";

export const parkingSpots: ParkingSpot[] = [
  {
    id: 1,
    title: "Secure Downtown Garage Spot",
    description:
      "Well-lit, covered garage spot in the heart of downtown. 24/7 access with key fob entry. Security cameras throughout. Close to public transit and restaurants. EV charging available.",
    address: "123 Main Street",
    city: "San Francisco",
    state: "CA",
    zip_code: "94102",
    price_per_hour: 5.0,
    price_per_day: 35.0,
    image_url:
      "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&q=80",
    spot_type: "garage",
    status: "available",
    amenities: ["Covered", "24/7 Access", "Security Camera", "EV Charging"],
    host_name: "Sarah Chen",
    rating: 4.9,
    review_count: 127,
  },
  {
    id: 2,
    title: "Spacious Residential Driveway",
    description:
      "Large driveway in a quiet neighborhood. Fits SUVs and trucks easily. 5 minutes from the freeway. Friendly neighborhood with low traffic.",
    address: "456 Oak Avenue",
    city: "Los Angeles",
    state: "CA",
    zip_code: "90012",
    price_per_hour: 3.0,
    price_per_day: 20.0,
    image_url:
      "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=800&q=80",
    spot_type: "driveway",
    status: "available",
    amenities: ["Spacious", "Residential Area", "Easy Access"],
    host_name: "Marcus Johnson",
    rating: 4.7,
    review_count: 89,
  },
  {
    id: 3,
    title: "Premium Underground Parking",
    description:
      "Climate-controlled underground parking in a luxury building. Concierge service available. Steps from shopping and dining in the Pearl District.",
    address: "789 Pearl Boulevard",
    city: "Portland",
    state: "OR",
    zip_code: "97209",
    price_per_hour: 7.0,
    price_per_day: 45.0,
    image_url:
      "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800&q=80",
    spot_type: "underground",
    status: "available",
    amenities: ["Underground", "Climate Controlled", "24/7 Access", "Concierge"],
    host_name: "Emily Rodriguez",
    rating: 4.95,
    review_count: 203,
  },
  {
    id: 4,
    title: "Airport Adjacent Lot",
    description:
      "Open lot 3 minutes from the terminal. Free shuttle every 15 minutes. Great for long-term parking without airport prices. Secure fencing and attendant on-site.",
    address: "1200 Aviation Way",
    city: "Denver",
    state: "CO",
    zip_code: "80249",
    price_per_hour: 2.5,
    price_per_day: 15.0,
    image_url:
      "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
    spot_type: "lot",
    status: "available",
    amenities: ["Shuttle Service", "Fenced", "Attendant", "Long-Term Friendly"],
    host_name: "David Kim",
    rating: 4.6,
    review_count: 312,
  },
  {
    id: 5,
    title: "Brooklyn Street Spot",
    description:
      "Reserved street parking in a safe, tree-lined neighborhood. Permit included. Walking distance to subway stations and local cafés.",
    address: "34 Maple Street",
    city: "Brooklyn",
    state: "NY",
    zip_code: "11201",
    price_per_hour: 4.0,
    price_per_day: 28.0,
    image_url:
      "https://images.unsplash.com/photo-1621929747188-0b4dc28498d6?w=800&q=80",
    spot_type: "street",
    status: "available",
    amenities: ["Permit Included", "Near Transit", "Well-Lit"],
    host_name: "Aisha Patel",
    rating: 4.8,
    review_count: 156,
  },
  {
    id: 6,
    title: "Tech Campus Garage",
    description:
      "Covered garage near major tech campuses in South Lake Union. Wide lanes, easy to navigate. Building has a café and restrooms.",
    address: "500 Boren Ave N",
    city: "Seattle",
    state: "WA",
    zip_code: "98109",
    price_per_hour: 6.0,
    price_per_day: 40.0,
    image_url:
      "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=800&q=80",
    spot_type: "garage",
    status: "available",
    amenities: ["Covered", "Wide Lanes", "Restrooms", "Security Camera"],
    host_name: "James Wright",
    rating: 4.75,
    review_count: 98,
  },
  {
    id: 7,
    title: "Stadium Event Parking",
    description:
      "Privately owned lot within walking distance of the stadium. Perfect for game days. Pre-book to guarantee your spot.",
    address: "88 Stadium Drive",
    city: "Chicago",
    state: "IL",
    zip_code: "60616",
    price_per_hour: 8.0,
    price_per_day: 50.0,
    image_url:
      "https://images.unsplash.com/photo-1470224114660-3f6686c562eb?w=800&q=80",
    spot_type: "lot",
    status: "available",
    amenities: ["Near Stadium", "Flat Surface", "Pre-Bookable"],
    host_name: "Lisa Thompson",
    rating: 4.5,
    review_count: 445,
  },
  {
    id: 8,
    title: "Beachside Driveway",
    description:
      "Private driveway two blocks from the beach. No more circling for parking on sunny days. Fits two cars.",
    address: "221 Ocean View Lane",
    city: "Miami",
    state: "FL",
    zip_code: "33139",
    price_per_hour: 4.5,
    price_per_day: 30.0,
    image_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
    spot_type: "driveway",
    status: "available",
    amenities: ["Near Beach", "Spacious", "Residential Area"],
    host_name: "Carlos Mendez",
    rating: 4.85,
    review_count: 178,
  },
];